import fs from 'node:fs';
import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {fixture,startServer,testUser,testPassword} from './support.mjs';
const f=await fixture();let server,browser;
try{
  server=await startServer(f);browser=await chromium.launch({headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(server.origin);await page.getByRole('button',{name:'Thêm vào giỏ'}).click();await page.reload();await page.waitForFunction(()=>document.getElementById('cart-count').textContent==='1');
  await page.getByRole('button',{name:'Tăng số lượng Trà sữa trân châu'}).click();assert.match(await page.locator('#cart-total').textContent(),/70/);await page.getByRole('button',{name:'Giảm số lượng Trà sữa trân châu'}).click();await page.getByRole('button',{name:'Xóa',exact:true}).click();assert.equal(await page.locator('#cart-count').textContent(),'0');await page.getByRole('button',{name:'Thêm vào giỏ'}).click();
  await page.locator('#search').fill('không tìm thấy');assert.equal(await page.locator('.product').count(),0);await page.locator('#search').fill('trân châu');assert.equal(await page.locator('.product').count(),1);
  await page.getByLabel('Họ tên',{exact:true}).fill('Khách trình duyệt');await page.getByLabel('Số điện thoại',{exact:true}).fill('0901234567');await page.getByLabel('Địa chỉ giao hàng').fill('123 Đường Trà Sữa');
  await page.route('**/api/orders',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({success:false,message:'Lỗi thử nghiệm'})}));
  await page.locator('#place-order').click();await page.waitForFunction(()=>document.getElementById('order-message').textContent.includes('Giỏ hàng được giữ lại'));assert.equal(await page.locator('#cart-count').textContent(),'1');
  await page.unroute('**/api/orders');await page.locator('#place-order').click();await page.waitForFunction(()=>document.getElementById('order-message').textContent.includes('Đặt hàng thành công'));assert.equal(await page.locator('#cart-count').textContent(),'0');assert.match(await page.locator('#order-message').textContent(),/MT-/);
  await page.reload();assert.equal(await page.locator('#cart-count').textContent(),'0');
  // Simulate a committed order whose response was lost; the retry must reuse its key.
  await page.getByRole('button',{name:'Thêm vào giỏ'}).click();await page.getByLabel('Họ tên',{exact:true}).fill('Khách mất phản hồi');await page.getByLabel('Số điện thoại',{exact:true}).fill('0901234567');await page.getByLabel('Địa chỉ giao hàng').fill('123 Đường Trà Sữa');
  await page.route('**/api/orders',async route=>{await route.fetch();await route.abort();});await page.locator('#place-order').click();await page.waitForFunction(()=>document.getElementById('order-message').textContent.includes('Giỏ hàng được giữ lại'));
  await page.unroute('**/api/orders');await page.locator('#place-order').click();await page.waitForFunction(()=>document.getElementById('order-message').textContent.includes('Đặt hàng thành công'));assert.equal((await f.db.execute('SELECT COUNT(*) AS n FROM Orders')).rows[0].n,2);
  await page.goto(server.origin+'/admin.html');await page.getByLabel('Tên đăng nhập').fill(testUser);await page.getByLabel('Mật khẩu',{exact:true}).fill(testPassword);await page.getByRole('button',{name:'Đăng nhập',exact:true}).click();await page.waitForFunction(()=>!document.getElementById('dashboard').hidden);
  await page.getByRole('button',{name:'Thêm sản phẩm'}).click();await page.getByLabel('Tên món',{exact:true}).fill('Trà sữa kiểm thử');await page.getByLabel('Giá (VNĐ)').fill('42000');await page.locator('#product-image').setInputFiles('public/images/tstt.jpg');await page.waitForFunction(()=>document.getElementById('image-message').textContent.includes('Đã chọn'));await page.getByRole('button',{name:'Lưu sản phẩm'}).click();await page.waitForFunction(()=>document.getElementById('admin-message').textContent==='Đã lưu sản phẩm.');assert.match(await page.locator('#admin-products').textContent(),/Trà sữa kiểm thử/);
  const uploaded=(await f.db.execute("SELECT ImageUrl FROM Products WHERE Name='Trà sữa kiểm thử'")).rows[0].ImageUrl;assert.match(uploaded,/^\/api\/images\//);
  await page.reload();await page.locator('#admin-products img').first().waitFor();await page.waitForFunction(()=>Array.from(document.querySelectorAll('#admin-products img')).some(img=>img.src.includes('/api/images/')&&img.complete&&img.naturalWidth>0));
  const savedCard=page.locator('#admin-products .product').filter({has:page.getByRole('heading',{name:'Trà sữa kiểm thử',exact:true})});await savedCard.getByRole('button',{name:'Sửa',exact:true}).click();assert.equal(await page.locator('#image-preview').getAttribute('src'),uploaded);await page.getByRole('button',{name:'Đóng',exact:true}).click();
  await page.getByRole('button',{name:'Thêm sản phẩm'}).click();assert.equal(await page.locator('#image-preview').isVisible(),false);await page.getByLabel('Tên món',{exact:true}).fill('Trà sữa kéo thả');await page.getByLabel('Giá (VNĐ)').fill('45000');
  await page.locator('#product-image').setInputFiles({name:'invalid.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg></svg>')});await page.waitForFunction(()=>document.getElementById('image-message').textContent.includes('Chỉ chọn ảnh'));assert.equal(await page.locator('#image-preview').isVisible(),false);
  const transfer=await page.evaluateHandle(base64=>{const dt=new DataTransfer();const bytes=Uint8Array.from(atob(base64),char=>char.charCodeAt(0));dt.items.add(new File([bytes],'dragged.jpg',{type:'image/jpeg'}));return dt;},fs.readFileSync('public/images/tstt.jpg').toString('base64'));
  await page.locator('#image-drop').dispatchEvent('drop',{dataTransfer:transfer});await transfer.dispose();await page.waitForFunction(()=>document.getElementById('image-message').textContent.includes('Đã chọn dragged.jpg'));assert.equal(await page.locator('#image-preview').isVisible(),true);
  await page.route('**/api/admin/images',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({success:false,message:'Không lưu được ảnh thử nghiệm'})}));await page.getByRole('button',{name:'Lưu sản phẩm'}).click();await page.waitForFunction(()=>document.getElementById('admin-message').textContent==='Không lưu được ảnh thử nghiệm');assert.equal(await page.locator('#product-form').isVisible(),true);assert.equal(await page.locator('#image-preview').isVisible(),true);
  await page.unroute('**/api/admin/images');await page.getByRole('button',{name:'Lưu sản phẩm'}).click();await page.waitForFunction(()=>document.getElementById('admin-message').textContent==='Đã lưu sản phẩm.');
  const retained=(await f.db.execute("SELECT ImageUrl FROM Products WHERE Name='Trà sữa kéo thả'")).rows[0].ImageUrl;assert.equal(retained,uploaded);
  const storePage=await browser.newPage();await storePage.goto(server.origin);await storePage.waitForFunction(()=>Array.from(document.querySelectorAll('.product img')).some(img=>img.src.includes('/api/images/')&&img.complete&&img.naturalWidth>0));await storePage.close();
  await page.getByRole('button',{name:'Đơn hàng',exact:true}).click();await page.locator('#admin-orders').getByRole('button',{name:'Xem chi tiết'}).first().click();await page.locator('#order-detail').getByRole('button',{name:'Đã xác nhận',exact:true}).click();await page.waitForFunction(()=>document.getElementById('order-detail').textContent.includes('Trạng thái: Đã xác nhận'));
  await page.getByRole('button',{name:'Đăng xuất'}).click();await page.waitForFunction(()=>document.getElementById('dashboard').hidden);
  // Verify visible empty/error/loading states and safe rendering.
  await page.route('**/api/products',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({success:true,products:[]})}));await page.goto(server.origin);await page.waitForFunction(()=>document.getElementById('status').textContent==='Chưa có sản phẩm đang bán.');await page.unroute('**/api/products');
  await page.route('**/api/products',route=>route.abort());await page.reload();await page.waitForFunction(()=>!document.getElementById('retry').hidden);await page.unroute('**/api/products');await page.locator('#retry').click();await page.getByRole('button',{name:'Thêm vào giỏ'}).first().waitFor();
  await page.route('**/api/products',async route=>{await new Promise(resolve=>setTimeout(resolve,400));await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({success:true,products:[{Id:1,Name:'<img src=x onerror=alert(1)>',Price:1,Description:'<script>alert(1)</script>',ImageUrl:'javascript:alert(1)'}]})});});
  await page.goto(server.origin);assert.match(await page.locator('#status').textContent(),/Đang tải/);await page.locator('.product h3').waitFor();assert.equal(await page.locator('.product script,.product img').count(),0);await page.unroute('**/api/products');
  for(const width of [390,1280]){await page.setViewportSize({width,height:850});await page.goto(server.origin);await page.getByRole('button',{name:'Thêm vào giỏ'}).first().waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
  assert.deepEqual(errors,[]);console.log('PASS browser: cart reload/quantity/search, failed/successful COD, lost-response retry, admin product/order/logout, file picker/drop/preview/persistence/upload failure, empty/error/loading/XSS, mobile/desktop layout.');
}finally{await browser?.close();await server?.close();f.close();}
